services:
  - type: web
    name: your-app-name
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      PORT: "8080"
      NODE_ENV: "production"
      MONGO_DB_URL: "mongodb+srv://nguyendong:OxXFpBJy0uPTZoRN@cluster0.9beth.mongodb.net/reacttestfresher"
      MIGRATION_USER_PASSWORD: "123456"
      JWT_ACCESS_SECRET: "JUSTARANDOMSTRINGACCESS"
      JWT_ACCESS_EXPIRE_IN: "10h"
      JWT_REFRESH_SECRET: "JUSTARANDOMSTRINGREFRESH"
      JWT_REFRESH_EXPIRE_IN: "1d"
